# Generated by Django 3.1.4 on 2020-12-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='submitdate',
        ),
    ]
